name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy subfolder to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages        # target branch
          folder: physically correct IBL and splitsum PBR (v1.02) # your project folder
